org: wallacevieira
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

package:
  individually: true

build:
  esbuild: 
    minify: true
    sourcemap: true

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST
